env:
  browser: true
  commonjs: true
  es2021: true
extends:
  - google
parserOptions:
  ecmaVersion: 13
rules: 
  semi: 0
  max-len:
    - 2
    - 120
    - ignoreStrings
  new-cap:
    - 2    
    - capIsNewExceptions: 
      - "Querier"
      - "SvgImage" 
      - "MapService"
  curly:
    - 2
    - multi
  valid-jsdoc: 1
  require-jsdoc: 0
  max-lines-per-function:
    - 2
    - 120
  brace-style:
    - 2
    - 1tbs
    - allowSingleLine: true
  linebreak-style: 0
  