version: '3.4'

services:
  atlas-backend:
    image: atlas-backend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ORACLEDB_USER: ${NODE_ORACLEDB_USER}
      NODE_ORACLEDB_PASSWORD: ${NODE_ORACLEDB_PASSWORD}
      NODE_ORACLEDB_CONNECTIONSTRING: ${NODE_ORACLEDB_CONNECTIONSTRING}
      LAJI_ACCESS_TOKEN: ${LAJI_ACCESS_TOKEN}
      LAJI_API_URL: ${LAJI_API_URL}
      USER_BLOCKLIST: ${USER_BLOCKLIST}
    ports:
      - 3000:3000
