openapi: 3.0.0
info:
  title: Atlas API
  version: 1.0.0
servers:
  - url: /api/v1
    description: at current host


paths:
  /map/{speciesId}/atlas:
    get:
      parameters:
        - $ref: "components.yaml#/parameters/speciesId"
        - name: type
          in: query
          type: string
          description: Selects the image format the map is returned in, possible values png or svg, default svg.
        - name: language
          in: query
          type: string
          description: Language of the map, possible values fi, en, sv.
        - name: scaling
          in: query
          type: number
          description: Scaling factor for the map resolution, if not set map has no resolution and width and height are set to 100%.
        - name: showActivity
          in: query
          type: boolean
          description: Selects if grid square activity category and its legend is rendered, defaults to false.
      summary: Get atlas map collection for a species.
      description: Atlas map collection contains all the atlas maps that are available for the concerned species.
      tags: 
        - map
      responses:
        '200':
          description: A an svg or png image for given species' atlas data.
          content:
            image/*:
              type: string
              format: png or svg
  /birdAssociation:
    get:
      summary: Get list of birdAssociation areas
      description: Bird association area collection containing their ID:s and names, ordered by ID
      tags:
        - birdAssociation
      responses:
        '200':
          description: An array of bird association areas
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  $ref: 'components.yaml#schemas/BirdAssociationArea'
              examples:
                JSON: 
                  $ref: 'components.yaml#/examples/birdAssociations'
  /grid:
    get:
      summary: Get an array of all atlas grid squares.
      description: "Each square resource represents a square area in the atlas grid."
      tags: 
        - grid
      responses:
        200:
          description: An array of grid resources.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  $ref: 'components.yaml#/schemas/GridData'
              examples:
                JSON:
                  $ref: 'components.yaml#/examples/grids'
  /grid/birdAssociation/{birdAssociationId}:
    get:
      parameters:
        - $ref: 'components.yaml#/parameters/birdAssociationId'
      summary: Get an array of atlas grid squares belonging to a bird association
      tags:
        - grid
      responses:
        200:
          description: An array of grid resources
          content: 
            application/json:
              schema: 
                type: object
                $ref: 'components.yaml#/schemas/BirdAssociationGridData'
              examples:
                JSON:
                  $ref: 'components.yaml#/examples/associationGrids'
  /grid/{gridId}:
    get:
      parameters:
        - $ref: 'components.yaml#/parameters/gridId'
      summary: Get a single atlas grid square.
      description: "Represents a square area in the atlas grid corresponding to the given gridId."
      tags: 
        - grid
      responses:
        200:
          description: A grid square object.
          content:
            application/json:
              schema:
                type: object
                $ref: 'components.yaml#/schemas/GridData'
              examples: 
                JSON:
                  $ref: 'components.yaml#/examples/grid1'
  /grid/{gridId}/atlas:
    get:      
      parameters:
        - $ref: 'components.yaml#/parameters/gridId'
        - name: language
          in: query
          type: string
          description: Language of the map, possible values fi, en, sv.
      summary: Get atlas data collection for an area.
      description: A collection of atlas data resources for an area.
      tags: 
        - grid
      responses:
        '200':
          description: Atlas data collection for an area.
          content:
            application/json:
              schema:
                $ref: 'components.yaml#/schemas/GridAtlasData'
              examples:
                JSON:
                  $ref: 'components.yaml#/examples/atlasDataExample'
  /taxon:
    get:
      summary: Get list of atlas species.
      description: A collection of species having been observed in atlas.
      tags:
        - taxon
      responses:
        '200':
          description: Collection of taxons
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  $ref: 'components.yaml#/schemas/Taxon'
                examples:
                  JSON:
                    $ref: 'components.yaml#/examples/taxa'
  /taxon/{taxonId}:
    get:
      parameters:
        - $ref: "components.yaml#/parameters/taxonId"
      summary: Get a single taxon and its neighbours in the taxonomic order
      tags:
        - taxon
      responses:
        '200':
          description: Taxon and its taxonomic order neighbours in the atlas species
          content:
            application/json:
              schema:
                type: object
                $ref: 'components.yaml#/schemas/TaxonWithNeighbours'
              examples:
                JSON:
                  $ref: 'components.yaml#/examples/taxon'