openapi: 3.0.0
info:
  title: Atlas API
  version: 1.0.0
servers:
  - url: /api/v1
    description: at current host


paths:
  /map/{speciesId}/atlas:
    get:
      parameters:
        - $ref: "components.yaml#/parameters/speciesId"
        - name: type
          in: query
          type: string
          description: Selects the image format the map is returned in, possible values png or svg, default svg.
        - name: language
          in: query
          type: string
          description: Language of the map, possible values fi, en, sv.
        - name: scaling
          in: query
          type: number
          description: Scaling factor for the map resolution, if not set map has no resolution and width and height are set to 100%.
        - name: showActivity
          in: query
          type: boolean
          description: Selects if grid square activity category and its legend is rendered, defaults to false.
      summary: Get atlas map collection for a species.
      description: Atlas map collection contains all the atlas maps that are available for the concerned species.
      tags: 
        - map
      responses:
        '200':
          description: A an svg or png image for given species' atlas data.
          content:
            image/*:
              type: string
              format: png or svg
  /birdAssociation:
    get:
      summary: Get list of birdAssociation areas
      description: Bird association area collection containing their ID:s and names, ordered by ID ascending
      tags:
        - birdAssociation
      responses:
        '200':
          description: An array of bird association areas
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  $ref: 'components.yaml#schemas/BirdAssociationArea'
              examples:
                JSON: 
                  $ref: 'components.yaml#/examples/birdAssociations'
  /birdAssociation/stats:
    get:
      summary: Get stats for all bird association areas, excluding norther Lapland
      description: Get stats for all bird association areas, excluding norther Lapland
      tags:
        - birdAssociation
      responses:
        '200':
          description: An array of bird association areas and their grid stats for whole Finland excluding northern Lapland.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  $ref: components.yaml#schemas/BirdAssociationStats
  /birdAssociation/stats/lappi:
    get:
      summary: Get stats for the 44 50km ykj grid squares for lapland higher that 740 ykj latitude
      description: Get stats for the 44 50km ykj grid squares for lapland higher that 740 ykj latitude
      tags:
        - birdAssociation
      responses:
        '200':
          description: An array of 50km grid squares for northern Lapland.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  $ref: components.yaml#schemas/LaplandStats
              examples:
                JSON:
                  $ref: 'components.yaml#/examples/laplandStats'
  /birdAssociation/{birdAssociationId}/stats:
    get:
      parameters:
        - $ref: 'components.yaml#/parameters/birdAssociationId'
      summary: Get bird association and statistics of its grids.
      description: Get bird association and statistics of its grids.
      tags:
        - birdAssociation
      responses:
        200:
          description: An object of bird association and its stats
          content: 
            application/json:
              schema: 
                type: object
                $ref: 'components.yaml#/schemas/BirdAssociationStats'
  /grid:
    get:
      summary: Get an object of grid stats (below ykj 740) and an array of all atlas grid squares.
      description: Get an object of grid stats (below ykj 740) and an array of all atlas grid squares.
      tags: 
        - grid
      responses:
        200:
          description: An array of grid resources and statistics of the grids.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: 'components.yaml#/schemas/FinlandStats'
                  - type: object
                    properties:
                      gridSquares:
                        type: array
                        items:
                          type: object
                          $ref: 'components.yaml#/schemas/GridData'
              examples:
                JSON:
                  $ref: 'components.yaml#/examples/grids'
  /grid/birdAssociation/{birdAssociationId}:
    get:
      parameters:
        - $ref: 'components.yaml#/parameters/birdAssociationId'
      summary: Get squares belonging to a bird association and statistics of the grids.
      description: Get an array of atlas grid squares belonging to a bird association and statistics of the grids.
      tags:
        - grid
      responses:
        200:
          description: An array of grid resources
          content: 
            application/json:
              schema: 
                type: object
                $ref: 'components.yaml#/schemas/BirdAssociationGridData'
              examples:
                JSON:
                  $ref: 'components.yaml#/examples/associationGrids'
  /grid/birdAssociation/{birdAssociationId}/taxon/{taxonId}:
    get:
      parameters:
        - $ref: 'components.yaml#/parameters/birdAssociationId'
        - $ref: 'components.yaml#/parameters/taxonId'
      summary: Get squares where the given species has been observed, in an area of the given bird association.
      description: Get squares where the given species has been observed, in an area of the given bird association.
      tags:
        - grid
      responses:
        200:
          description: An array of grid data
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'components.yaml#/schemas/AssociationAndTaxonGrid'
  /grid/{gridId}:
    get:
      parameters:
        - $ref: 'components.yaml#/parameters/gridId'
      summary: Information about a single bird atlas square.
      description: Information about a single bird atlas square.
      tags: 
        - grid
      responses:
        200:
          description: A grid square object.
          content:
            application/json:
              schema:
                type: object
                $ref: 'components.yaml#/schemas/GridData'
              examples: 
                JSON:
                  $ref: 'components.yaml#/examples/grid1'
  /grid/{gridId}/atlas:
    get:      
      parameters:
        - $ref: 'components.yaml#/parameters/gridId'
        - name: language
          in: query
          type: string
          description: Language of the map, possible values fi, en, sv.
      summary: Information about a single bird atlas square, with a list of species observed.
      description: Information about a single bird atlas square with a list of species observed.
      tags: 
        - grid
      responses:
        '200':
          description: Atlas data collection for an area.
          content:
            application/json:
              schema:
                $ref: 'components.yaml#/schemas/GridAtlasData'
              examples:
                JSON:
                  $ref: 'components.yaml#/examples/atlasDataExample'
  /taxon:
    get:
      summary: Get list of bird atlas species.
      description: A collection of species belonging to the bird atlas.
      tags:
        - taxon
      responses:
        '200':
          description: Collection of taxons
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  $ref: 'components.yaml#/schemas/Taxon'
              examples:
                JSON:
                  $ref: 'components.yaml#/examples/taxa'
  /taxon/{taxonId}:
    get:
      parameters:
        - $ref: "components.yaml#/parameters/taxonId"
      summary: Get a single taxon and its neighbours in the taxonomic order
      tags:
        - taxon
      responses:
        '200':
          description: Atlas taxon with previous & next taxon, based on taxonomic order.
          content:
            application/json:
              schema:
                type: object
                $ref: 'components.yaml#/schemas/TaxonWithNeighbours'
              examples:
                JSON:
                  $ref: 'components.yaml#/examples/taxon'
  /taxon/{taxonId}/gridStats:
    get:
      parameters:
        - $ref: "components.yaml#/parameters/taxonId"
      summary: Get grid square counts for different atlas classes
      tags:
        - taxon
      responses:
        '200':
          description: Count of grid squares in different atlas classes
          content:
            application/json:
              schema:
                type: object
                $ref: 'components.yaml#/schemas/TaxonSquareCount'
              examples:
                JSON:
                  $ref: 'components.yaml#/examples/taxonSquares'
  /taxon/biomon/{taxonSetId}/{grid}:
    get:
      parameters:
        - $ref: "components.yaml#/parameters/taxonSetId"
        - $ref: "components.yaml#/parameters/grid100km"
      summary: Get a species abundance list from a taxonSet and a square.
      description: Get species for a specific taxonSet and square, ordered by descending abundance. Abundance is calculated by number of complete lists containing the taxon, from nearby squares during the last few weeks. If there are not enough complete lists, falls back to using data from whole Finland.
      tags:
        - taxon
      responses:
        '200':
          description: Taxon list ordered primarily by number for complete list observations (desc), secondarily by taxonomic order (asc).
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  $ref: 'components.yaml#/schemas/Taxon'
              examples:
                JSON:
                  $ref: 'components.yaml#/examples/taxa'
