apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: atlas-backend-dev
  name: atlas-backend-dev
spec:
  replicas: 1
  selector:
    io.kompose.service: atlas-backend-dev
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: atlas-backend-dev
    spec:
      containers:
        - env:
            - name: NODE_ORACLEDB_CONNECTIONSTRING
              valueFrom:
                secretKeyRef:
                  key: NODE_ORACLEDB_CONNECTIONSTRING
                  name: atlas-oracle
            - name: NODE_ORACLEDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: NODE_ORACLEDB_PASSWORD
                  name: atlas-oracle
            - name: NODE_ORACLEDB_USER
              valueFrom:
                secretKeyRef:
                  key: NODE_ORACLEDB_USER
                  name: atlas-oracle
          image: luomus/atlas-backend
          name: atlas-backend-dev
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - atlas-backend-dev
        from:
          kind: ImageStreamTag
          name: atlas-backend-dev:testing
      type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
