apiVersion: v1
kind: BuildConfig
metadata:
  creationTimestamp: null
  name: atlas-backend-dev
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'atlas-backend-dev:testing'
  runPolicy: Serial
  source:
    git:
      uri: 'https://github.com/luomus/atlas-backend.git'
      ref: 'development'
  strategy:
    type: Docker
  triggers:
    - github:
        secretReference:
          name: atlas-backend-webhook
      type: GitHub