apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: atlas-backend-dev
  name: atlas-backend-dev
spec:
  lookupPolicy:
    local: false
  tags:
    - annotations: null
      from:
        kind: DockerImage
        name: luomus/atlas-backend:testing
      generation: null
      importPolicy: {}
      name: "testing"
status:
  dockerImageRepository: "luomus/atlas-backend"
